import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useI18n } from '@/i18n';
import { fetchDocumentationSnapshot } from '@/services/docsApi';
import type { DocumentationSnapshot } from '@/types/documentation';
import { DocCard, DocPre, DocSection, DocTable } from './components/DocUi';

const SECTION_IDS = [
  'about',
  'architecture',
  'structure',
  'database',
  'workflow',
  'codes',
  'ipc',
  'settings',
  'hotkeys',
  'contacts',
  'changelog',
] as const;

type SectionId = (typeof SECTION_IDS)[number];

const SECTION_TITLE_KEYS = {
  about: 'docs.sectionAbout',
  architecture: 'docs.sectionArchitecture',
  structure: 'docs.sectionStructure',
  database: 'docs.sectionDatabase',
  workflow: 'docs.sectionWorkflow',
  codes: 'docs.sectionCodes',
  ipc: 'docs.sectionIpc',
  settings: 'docs.sectionSettings',
  hotkeys: 'docs.sectionHotkeys',
  contacts: 'docs.sectionContacts',
  changelog: 'docs.sectionChangelog',
} as const satisfies Record<SectionId, import('@/i18n/types').TranslationKey>;

export function DocumentationPage() {
  const { t } = useI18n();
  const location = useLocation();
  const [snapshot, setSnapshot] = useState<DocumentationSnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState<SectionId>('about');

  const loadSnapshot = () => {
    setLoading(true);
    setError(null);
    fetchDocumentationSnapshot()
      .then(setSnapshot)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadSnapshot();
  }, []);

  useEffect(() => {
    const hash = location.hash.replace('#', '') as SectionId;
    if (SECTION_IDS.includes(hash)) {
      setActiveSection(hash);
      document.getElementById(hash)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [location.hash]);

  const generatedLabel = useMemo(() => {
    if (!snapshot) return '';
    return new Date(snapshot.generatedAt).toLocaleString('uk-UA');
  }, [snapshot]);

  return (
    <div className="flex h-full min-h-0">
      <aside className="hidden w-56 shrink-0 overflow-y-auto border-r border-surface-border bg-white p-4 lg:block">
        <div className="mb-4">
          <Link to="/" className="text-sm text-brand-600 hover:text-brand-700">
            ← {t('docs.backHome')}
          </Link>
        </div>
        <h1 className="mb-1 text-base font-semibold text-slate-900">{t('docs.title')}</h1>
        <p className="mb-4 text-xs text-slate-400">{t('docs.autoGenerated')}</p>
        <nav className="space-y-1">
          {SECTION_IDS.map((id) => (
            <a
              key={id}
              href={`#${id}`}
              onClick={() => setActiveSection(id)}
              className={[
                'block rounded-lg px-3 py-2 text-sm transition-colors',
                activeSection === id
                  ? 'bg-brand-50 font-medium text-brand-700'
                  : 'text-slate-600 hover:bg-slate-100',
              ].join(' ')}
            >
              {t(SECTION_TITLE_KEYS[id])}
            </a>
          ))}
        </nav>
      </aside>

      <div className="min-h-0 flex-1 overflow-y-auto p-6">
        <div className="mx-auto max-w-4xl">
          <header className="mb-8 flex flex-wrap items-start justify-between gap-4">
            <div>
              <h1 className="text-2xl font-semibold text-slate-900">{t('docs.title')}</h1>
              <p className="mt-1 text-sm text-slate-500">{t('docs.subtitle')}</p>
            </div>
            <button
              type="button"
              onClick={loadSnapshot}
              disabled={loading}
              className="rounded-lg border border-surface-border px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-50"
            >
              🔄 {t('docs.refresh')}
            </button>
          </header>

          {loading && !snapshot ? (
            <div className="py-20 text-center text-sm text-slate-400">{t('common.loading')}</div>
          ) : error ? (
            <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
              {error}
            </div>
          ) : snapshot ? (
            <div className="space-y-10">
              <p className="text-xs text-slate-400">
                {t('docs.generatedAt', { date: generatedLabel })} · v{snapshot.appVersion}
              </p>

              <DocSection id="about" title={t('docs.sectionAbout')}>
                <p>{t('docs.about.p1')}</p>
                <p>{t('docs.about.p2')}</p>
                <p>{t('docs.about.p3')}</p>
                <DocCard title={t('docs.about.workflowTitle')}>
                  <p>{t('docs.about.p4')}</p>
                </DocCard>
              </DocSection>

              <DocSection id="architecture" title={t('docs.sectionArchitecture')}>
                <p>{t('docs.architecture.intro')}</p>
                <DocTable
                  headers={[t('docs.colLayer'), t('docs.colTechnology'), t('docs.colRole')]}
                  rows={[
                    ['Frontend', 'React + TypeScript + Tailwind', t('docs.architecture.frontend')],
                    ['Desktop', 'Electron', t('docs.architecture.electron')],
                    ['Data', 'SQLite (better-sqlite3)', t('docs.architecture.sqlite')],
                    ['Bridge', 'IPC (contextBridge)', t('docs.architecture.ipc')],
                    ['Backend', 'Repository Pattern', t('docs.architecture.repo')],
                  ]}
                />
                <DocPre>{`┌─────────────────────────────────────────────────────────┐
│                    Renderer (React)                      │
│  pages · components · hooks · services · NavigationContext│
└───────────────────────────┬─────────────────────────────┘
                            │ window.edumost (preload)
                            ▼
┌─────────────────────────────────────────────────────────┐
│                   Main Process (Electron)                  │
│              ipc/handlers.ts → repositories/             │
└───────────────────────────┬─────────────────────────────┘
                            │
                            ▼
                    SQLite (edumost.db)`}</DocPre>
              </DocSection>

              <DocSection id="structure" title={t('docs.sectionStructure')}>
                <p>{t('docs.structure.intro')}</p>
                <DocTable
                  headers={[t('docs.colPath'), t('docs.colDescription')]}
                  rows={snapshot.projectFolders.map((folder) => [folder.path, folder.description])}
                />
                <p className="text-xs text-slate-500">{t('docs.structure.routesNote')}</p>
                <DocTable
                  headers={[t('docs.colRoute'), t('docs.colComponent'), t('docs.colNote')]}
                  rows={snapshot.routes.map((route) => [
                    route.path,
                    route.component,
                    route.note ?? '—',
                  ])}
                />
              </DocSection>

              <DocSection id="database" title={t('docs.sectionDatabase')}>
                <p>{t('docs.database.intro')}</p>
                {snapshot.tables.map((table) => (
                  <DocCard key={table.name} title={table.name}>
                    <p className="mb-3">{table.purpose}</p>
                    <p className="mb-2 text-xs text-slate-500">
                      {t('docs.database.migrations')}: {table.migrations.join(', ')}
                    </p>
                    <DocTable
                      headers={[t('docs.colField'), t('docs.colType')]}
                      rows={table.columns.map((col) => [col.name, col.type])}
                    />
                    {table.foreignKeys.length > 0 ? (
                      <div className="mt-3">
                        <p className="mb-2 text-xs font-semibold uppercase text-slate-500">
                          {t('docs.database.relations')}
                        </p>
                        <DocTable
                          headers={[t('docs.colField'), t('docs.colReferences'), 'ON DELETE']}
                          rows={table.foreignKeys.map((fk) => [
                            fk.column,
                            fk.references,
                            fk.onDelete ?? '—',
                          ])}
                        />
                      </div>
                    ) : null}
                  </DocCard>
                ))}
              </DocSection>

              <DocSection id="workflow" title={t('docs.sectionWorkflow')}>
                <p>{t('docs.workflow.intro')}</p>
                <DocPre>{`Предмет → Клас → Розділ → Тема → Урок → Матеріали → Експорт

1. Оберіть предмет і клас у лівій панелі (Knowledge Explorer)
2. Оберіть розділ програми
3. Створіть або редагуйте тему (Topic Editor)
4. Додайте урок до теми (Lesson Studio)
5. Прикріпіть матеріали (LessonResources)
6. Експортуйте БД або довідники через Налаштування / Довідники`}</DocPre>
              </DocSection>

              <DocSection id="codes" title={t('docs.sectionCodes')}>
                <p>{t('docs.codes.intro')}</p>
                <DocTable
                  headers={[
                    t('docs.colEntity'),
                    t('docs.colFormat'),
                    t('docs.colMethod'),
                    t('docs.colDescription'),
                  ]}
                  rows={snapshot.codeRules.map((rule) => [
                    rule.entity,
                    <code key={rule.entity}>{rule.format}</code>,
                    <code key={`${rule.entity}-m`}>{rule.method}</code>,
                    rule.description,
                  ])}
                />
              </DocSection>

              <DocSection id="ipc" title={t('docs.sectionIpc')}>
                <p>{t('docs.ipc.intro', { count: snapshot.ipcChannels.length })}</p>
                <DocTable
                  headers={[t('docs.colChannel'), t('docs.colHandlers')]}
                  rows={snapshot.ipcChannels.map((item) => [
                    <code key={item.channel}>{item.channel}</code>,
                    item.handlers.length > 0 ? item.handlers.join(', ') : '—',
                  ])}
                />
                <p className="text-xs text-slate-500">{t('docs.ipc.reposTitle')}</p>
                <DocTable
                  headers={[t('docs.colRepository'), t('docs.colMethods')]}
                  rows={snapshot.repositories.map((repo) => [
                    repo.className,
                    repo.methods.join(', '),
                  ])}
                />
              </DocSection>

              <DocSection id="settings" title={t('docs.sectionSettings')}>
                <p>{t('docs.settings.intro')}</p>
                <DocTable
                  headers={[t('docs.colField'), t('docs.colType'), t('docs.colDescription')]}
                  rows={snapshot.settingsFields.map((field) => [
                    field.key,
                    field.type,
                    field.description,
                  ])}
                />
                <DocCard title={t('docs.settings.featuresTitle')}>
                  <ul className="list-disc space-y-1 pl-5">
                    <li>{t('docs.settings.exportDb')}</li>
                    <li>{t('docs.settings.importDb')}</li>
                    <li>{t('docs.settings.backup')}</li>
                    <li>{t('docs.settings.materials')}</li>
                    <li>{t('docs.settings.autoBackup')}</li>
                  </ul>
                </DocCard>
              </DocSection>

              <DocSection id="hotkeys" title={t('docs.sectionHotkeys')}>
                <DocTable
                  headers={[t('docs.colKeys'), t('docs.colAction'), t('docs.colStatus')]}
                  rows={snapshot.hotkeys.map((hotkey) => [
                    <kbd key={hotkey.keys} className="rounded border px-1.5 py-0.5 text-xs">
                      {hotkey.keys}
                    </kbd>,
                    hotkey.action,
                    hotkey.implemented ? t('docs.hotkeyYes') : t('docs.hotkeyNo'),
                  ])}
                />
              </DocSection>

              <DocSection id="contacts" title={t('docs.sectionContacts')}>
                <DocTable
                  headers={[t('docs.colItem'), t('docs.colValue')]}
                  rows={[
                    [t('docs.contacts.author'), t('docs.contacts.authorValue')],
                    [t('docs.contacts.github'), t('docs.contacts.githubValue')],
                    [t('docs.contacts.version'), `EduMost Studio ${snapshot.appVersion}`],
                    [t('docs.contacts.electron'), snapshot.electronVersion],
                  ]}
                />
              </DocSection>

              <DocSection id="changelog" title={t('docs.sectionChangelog')}>
                {snapshot.changelog.map((entry) => (
                  <DocCard key={entry.migration} title={`${entry.version} — ${entry.migration}`}>
                    <ul className="list-disc space-y-1 pl-5">
                      {entry.features.map((feature) => (
                        <li key={feature}>{feature}</li>
                      ))}
                    </ul>
                  </DocCard>
                ))}
              </DocSection>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}
