import { BilingualText } from '@/components/content/BilingualText';
import { useI18n } from '@/i18n';
import type { LessonDetail } from '@/types/database';
import type { LessonFormData } from '../types';
import { LessonSectionCard } from './LessonSectionCard';
import { LessonTopicsList } from './LessonTopicsList';

const fieldClass =
  'w-full min-w-0 rounded-lg border border-surface-border bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100';

export function LessonBasicInfoPanel({
  detail,
  form,
  isCreate,
  onChange,
}: {
  detail: LessonDetail;
  form: LessonFormData;
  isCreate?: boolean;
  onChange: (patch: Partial<LessonFormData>) => void;
}) {
  const { t } = useI18n();
  const primaryTopic =
    detail.topics?.find((topic) => topic.is_primary === 1) ?? detail.topics?.[0];
  const topics = detail.topics ?? [];

  return (
    <LessonSectionCard number={1} title={t('lessonStudio.basicInfo')}>
      <div className="space-y-4">
        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('lessonStudio.lessonCode')}
          </label>
          <input
            type="text"
            value={form.code}
            onChange={(e) => onChange({ code: e.target.value })}
            className={`${fieldClass} font-mono ${isCreate ? 'bg-surface-muted' : ''}`}
          />
          {isCreate ? (
            <p className="mt-1.5 text-xs text-slate-400">{t('editor.codeAutoGenerated')}</p>
          ) : null}
        </div>

        {isCreate ? (
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('lessonStudio.lessonTitle')}
            </label>
            <div className="space-y-2">
              <input
                type="text"
                value={form.title_pl}
                onChange={(e) => onChange({ title_pl: e.target.value })}
                placeholder={t('content.labelPl')}
                className={fieldClass}
                required
              />
              <input
                type="text"
                value={form.title_ua}
                onChange={(e) => onChange({ title_ua: e.target.value })}
                placeholder={t('content.labelUa')}
                className={fieldClass}
                required
              />
            </div>
          </div>
        ) : null}

        {primaryTopic ? (
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('lessonStudio.primaryTopic')}
            </label>
            <div className="rounded-lg border border-surface-border bg-surface-muted px-3 py-2.5">
              <div className="font-mono text-xs font-semibold text-brand-700">
                {primaryTopic.topic_code}
              </div>
              <BilingualText
                textPl={primaryTopic.topic_name_pl}
                textUa={primaryTopic.topic_name_ua}
                variant="compact"
              />
            </div>
          </div>
        ) : null}

        {primaryTopic ? (
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('lessonStudio.section')}
            </label>
            <input
              type="text"
              value={primaryTopic.section_name_ua}
              readOnly
              className={`${fieldClass} bg-surface-muted text-slate-500`}
            />
          </div>
        ) : null}

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('table.class')}
            </label>
            {isCreate ? (
              <select
                value={form.school_class}
                onChange={(e) => onChange({ school_class: Number(e.target.value) })}
                className={fieldClass}
              >
                {Array.from({ length: 8 }, (_, index) => index + 1).map((schoolClass) => (
                  <option key={schoolClass} value={schoolClass}>
                    {schoolClass}
                  </option>
                ))}
              </select>
            ) : (
              <input
                type="number"
                min={1}
                max={8}
                value={form.school_class}
                onChange={(e) => onChange({ school_class: Number(e.target.value) || 1 })}
                className={fieldClass}
              />
            )}
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('lessonStudio.duration')}
            </label>
            <div className="flex items-center gap-2">
              <input
                type="number"
                min={0}
                value={form.duration ?? ''}
                onChange={(e) =>
                  onChange({
                    duration: e.target.value === '' ? null : Number(e.target.value),
                  })
                }
                className={fieldClass}
              />
              <span className="shrink-0 text-xs text-slate-500">{t('lessonStudio.minutes')}</span>
            </div>
          </div>
        </div>

        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('lessonStudio.lessonType')}
          </label>
          <input
            type="text"
            value={form.lesson_type}
            onChange={(e) => onChange({ lesson_type: e.target.value })}
            className={fieldClass}
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('lessonStudio.status')}
            </label>
            <select
              value={form.status}
              onChange={(e) => onChange({ status: e.target.value })}
              className={fieldClass}
            >
              <option value="Draft">Draft</option>
              <option value="Published">Published</option>
              <option value="Archived">Archived</option>
            </select>
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium text-slate-600">
              {t('editor.status')}
            </label>
            <select
              value={form.is_active}
              onChange={(e) => onChange({ is_active: Number(e.target.value) })}
              className={fieldClass}
            >
              <option value={1}>{t('editor.statusActive')}</option>
              <option value={0}>{t('editor.statusInactive')}</option>
            </select>
          </div>
        </div>

        {topics.length > 0 ? (
          <div className="border-t border-surface-border pt-4">
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t('lessonStudio.relatedTopics')}
            </h3>
            <LessonTopicsList topics={topics} />
          </div>
        ) : null}
      </div>
    </LessonSectionCard>
  );
}
