import { useI18n } from '@/i18n';
import { useNavigation } from '@/context/NavigationContext';
import type { Section } from '@/types/database';
import type { TopicFormData } from '../types';

const fieldClass =
  'w-full rounded-lg border border-surface-border bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100';

export function TopicBasicInfoPanel({
  form,
  sections,
  isCreate,
  onChange,
  onSectionsChange,
}: {
  form: TopicFormData;
  sections: Section[];
  isCreate?: boolean;
  onChange: (patch: Partial<TopicFormData>) => void;
  onSectionsChange?: () => void;
}) {
  const { t } = useI18n();
  const nav = useNavigation();

  const handleSectionSelect = (sectionId: number) => {
    const section = sections.find((item) => item.id === sectionId);
    if (!section) return;
    onChange({ section_id: section.id, section_name: section.name_ua });
  };

  const openSectionCreate = () => {
    nav.openSectionCreateModal((section) => {
      onChange({ section_id: section.id, section_name: section.name_ua });
      onSectionsChange?.();
      nav.refreshExplorer();
    });
  };

  return (
    <section className="rounded-xl border border-surface-border bg-white p-5">
      <h2 className="mb-4 text-xs font-semibold uppercase tracking-wide text-slate-400">
        {t('editor.basicInfo')}
      </h2>
      <div className="space-y-4">
        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('editor.topicCode')}
          </label>
          <input
            type="text"
            value={form.code}
            onChange={(e) => onChange({ code: e.target.value })}
            className={`${fieldClass} font-mono ${isCreate ? 'bg-surface-muted' : ''}`}
            required
          />
          {isCreate ? (
            <p className="mt-1.5 text-xs text-slate-400">{t('editor.codeAutoGenerated')}</p>
          ) : null}
        </div>

        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('table.namePl')} / {t('table.nameUa')}
          </label>
          <div className="space-y-2">
            <input
              type="text"
              value={form.name_pl}
              onChange={(e) => onChange({ name_pl: e.target.value })}
              placeholder={t('content.labelPl')}
              className={fieldClass}
              required
            />
            <input
              type="text"
              value={form.name_ua}
              onChange={(e) => onChange({ name_ua: e.target.value })}
              placeholder={t('content.labelUa')}
              className={fieldClass}
              required
            />
          </div>
        </div>

        <div>
          <div className="mb-1.5 flex items-center justify-between gap-2">
            <label className="text-xs font-medium text-slate-600">{t('editor.section')}</label>
            <button
              type="button"
              onClick={openSectionCreate}
              className="text-xs font-medium text-brand-700 hover:text-brand-800"
            >
              {t('action.newSection')}
            </button>
          </div>
          <select
            value={form.section_id || ''}
            onChange={(e) => handleSectionSelect(Number(e.target.value))}
            className={fieldClass}
            required
          >
            <option value="" disabled>
              {t('lessonStudio.selectSection')}
            </option>
            {sections.map((section) => (
              <option key={section.id} value={section.id}>
                {section.name_ua} ({section.code})
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('table.class')}
          </label>
          <select
            value={form.school_class}
            onChange={(e) => onChange({ school_class: Number(e.target.value) })}
            className={fieldClass}
          >
            {Array.from({ length: 8 }, (_, index) => index + 1).map((schoolClass) => (
              <option key={schoolClass} value={schoolClass}>
                {schoolClass}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-600">
            {t('editor.status')}
          </label>
          <select
            value={form.is_active}
            onChange={(e) => onChange({ is_active: Number(e.target.value) })}
            className={fieldClass}
          >
            <option value={1}>{t('editor.statusActive')}</option>
            <option value={0}>{t('editor.statusInactive')}</option>
          </select>
        </div>
      </div>
    </section>
  );
}
